/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegisterResponse } from '../../models/register-response';

export interface GetAllOwnersOfBookByBookTitle$Params {
  bookTitle: string;
}

export function getAllOwnersOfBookByBookTitle(http: HttpClient, rootUrl: string, params: GetAllOwnersOfBookByBookTitle$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RegisterResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllOwnersOfBookByBookTitle.PATH, 'get');
  if (params) {
    rb.query('bookTitle', params.bookTitle, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RegisterResponse>>;
    })
  );
}

getAllOwnersOfBookByBookTitle.PATH = '/users';
