/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookRequest {
  authorName: string;
  coverPath?: string;
  id?: number;
  isbn: string;
  shareable?: boolean;
  synopsis?: string;
  title: string;
}
