/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedBookResponse {
  archived?: boolean;
  authorName?: string;
  borrowedAt?: string;
  borrowedBy?: string;
  cover?: string;
  coverPath?: string;
  id?: number;
  isbn?: string;
  owner?: string;
  rate?: number;
  returned?: boolean;
  returnedAt?: string;
  shareable?: boolean;
  synopsis?: string;
  title?: string;
}
