/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WishlistEntryResponse } from '../models/wishlist-entry-response';
export interface PageResponseWishlistEntryResponse {
  content?: Array<WishlistEntryResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
