/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserCardDto {
  avatar?: string;
  firstname?: string;
  lastname?: string;
  location?: string;
}
