/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookResponse } from '../models/book-response';
export interface WishlistEntryResponse {
  bookResponse?: BookResponse;
  dateAdded?: string;
  userFullName?: string;
}
