/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BorrowedBookResponse } from '../../models/borrowed-book-response';

export interface ReturnBook$Params {
  bookId: number;
}

export function returnBook(http: HttpClient, rootUrl: string, params: ReturnBook$Params, context?: HttpContext): Observable<StrictHttpResponse<BorrowedBookResponse>> {
  const rb = new RequestBuilder(rootUrl, returnBook.PATH, 'patch');
  if (params) {
    rb.query('bookId', params.bookId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BorrowedBookResponse>;
    })
  );
}

returnBook.PATH = '/books/return/{bookId}';
