/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { BookRequest } from './models/book-request';
export type { BookResponse } from './models/book-response';
export type { BorrowedBookResponse } from './models/borrowed-book-response';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedbackResponse } from './models/feedback-response';
export type { LoginRequest } from './models/login-request';
export type { LoginResponse } from './models/login-response';
export type { PageResponseBookResponse } from './models/page-response-book-response';
export type { PageResponseBorrowedBookResponse } from './models/page-response-borrowed-book-response';
export type { PageResponseFeedbackResponse } from './models/page-response-feedback-response';
export type { PageResponseWishlistEntryResponse } from './models/page-response-wishlist-entry-response';
export type { RegisterRequest } from './models/register-request';
export type { RegisterResponse } from './models/register-response';
export type { UserCardDto } from './models/user-card-dto';
export type { WishlistEntryResponse } from './models/wishlist-entry-response';
